SET IDENTITY_INSERT [dbo].[SystemUser] ON
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1, N'sysAdmin', N'系统管理员', N'P@ssword', N'1', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1001, N'奚跃华', N'奚跃华', N'jugonglu', N'2', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1002, N'孙正荣', N'孙正荣', N'jugonglu', N'3', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1003, N'冯继芳', N'冯继芳', N'jugonglu', N'4', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1004, N'陆晓庆', N'陆晓庆', N'jugonglu', N'1,4', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1005, N'杭伟平', N'杭伟平', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1006, N'丁炳仁', N'丁炳仁', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1007, N'陈文祥', N'陈文祥', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1008, N'吴建平', N'吴建平', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1009, N'陶春红', N'陶春红', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1010, N'徐铭灏', N'徐铭灏', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1011, N'李治文', N'李治文', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1012, N'李波', N'李波', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1013, N'杨礼青', N'杨礼青', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1014, N'李广学', N'李广学', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1015, N'周才顺', N'周才顺', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1016, N'彭文军', N'彭文军', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1017, N'刘才胜', N'刘才胜', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1018, N'邓根发', N'邓根发', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1019, N'刘颂福', N'刘颂福', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1020, N'马  华', N'马  华', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1021, N'杨华平', N'杨华平', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1022, N'华  中', N'华  中', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1023, N'赖罗发', N'赖罗发', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1024, N'赖章华', N'赖章华', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1025, N'马金海', N'马金海', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1026, N'陈珍云', N'陈珍云', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1027, N'陶志文', N'陶志文', N'jugonglu', N'5', 0)
INSERT [dbo].[SystemUser] ([SystemUserID], [Code], [Name], [Password], [Roles], [Deleted]) VALUES (1028, N'唐观长', N'唐观长', N'jugonglu', N'5', 0)
SET IDENTITY_INSERT [dbo].[SystemUser] OFF
go
